app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/', 'NewsController@index');
        Route::resource('news', 'NewsController');
        Route::resource('categories', 'CategoryController');
    });
    Route::get('welcome/{locale}', function ($locale) {
        App::setLocale($locale);

        //
    });
    Route::get('/', 'HomeController@index');
    Route::resource('news', 'HomeController', ['except' => ['update', 'destroy']]);

});
//
//App::missing(function($exception)
//{
//    return Response::view('error', array(), 404);
//});

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.block.head_site')
</head>

<body>
<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">My Newsblog</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse navbar-left">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">{{ trans('message.home') }}</a></li>
                        <li><a style="color:white; cursor:pointer;" data-toggle="modal"
                               data-target="#myModal">{{ trans('message.addnews') }}</a></li>
                    </ul>
                </div>
                <div id="navbar" class="navbar-collapse collapse navbar-right">
                    <ul class="nav navbar-nav">
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>

                        @else
                            <li><a href="{{ url('/admin') }}">{{ trans('message.en-admin') }}</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a>
                                    </li>
                                </ul>
                            </li>

                        @endif
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>
<div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <div class="row">
        @include('flash::message')
        @yield('content')
    </div><!-- /.row -->

    <!-- FOOTER -->
    <footer>
    </footer>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">{{ trans('message.addnews') }}</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['action' => ['HomeController@store'],'files' => true, "id"=>"mod-form"]) !!}
                    @include('layouts.simple_form')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" id="save" class="btn btn-primary">Add</button>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div><!-- /.container -->
@include('layouts.block.footer')
</body>
</html>

resources/views/home.blade.php
@extends('app')
@section('content')

    <h1 class="page-header">{{ trans('message.header') }}</h1>
    <div class="container-fluid">
        @if(count($news))
            <div class="row">
                <div class="col-md-4">
                    <h3>{{ trans('message.choosecat') }}</h3>
                </div>
                <div class="col-md-8 text-left">
                    <div id="filters" class="button-group">
                        <button class="btn btn-primary btn-lg" data-filter="*">{{ trans('message.showcat') }}</button>
                        @foreach($cats as $cat)
                            <button class="btn btn-primary btn-lg" data-filter=".{{$cat->id}}">{{$cat->title}}</button>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="container-fluid no-gutter">

                <div id="posts" class="row">
                    @foreach($news as $new)

                        <div id="1" class="item {{$new->category_id}} col-sm-3">

                            <div class="item-wrap">
                                <h4>{!! link_to_route('news.show', $new->title, [$new->id]) !!}</h4>
                                <img class="img-responsive img-thumbnail" src="{{$new->tn_image_path}}">
                                <div class="text-right">{{$new->published_at }}</div>
                                <p class="prew">{!!  substr(strip_tags($new->content), 0, 100)  !!}</p>
                                <div class="row text-center">
                                    {!! link_to_route('news.show', trans('message.more'), [$new->id],['class'=>'btn btn-primary']) !!}
                                </div>

                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        @else
            <h2>{{ trans('message.sorry') }}</h2>
        @endif
    </div>
@endsection

resources/views/show_news.blade.php
@extends('app')
@section('content')

    <h1 class="page-header">{{$news->title}}</h1>

    <div class="container-fluid no-gutter">
        <div class="text-left">{{ $news->published_at }}</div>
        <div class="row">
            <img class="img-thumbnail my-image" src="{{$news->image_path}}">{!!$news->content!!}
        </div>
    </div>



@endsection